---
- name: Install dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Aumentar memoria virtual
  sysctl:
    name: vm.max_map_count
    value: 262144
    sysctl_set: yes
    state: present
