pipeline {
    agent any
    stages{
        stage('Baking Calculator') {
            steps{
                sh """
                cd app-bake
                packer build -var "key_file=${env.key_file}" -var "keypair_name=${keypair_name}" .
                """
            }
        }
    }
}
